# WARNING: this file is not suitable for production, please use with caution
version: '3'

services:
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - 22181:2181

  kafka:
    image: confluentinc/cp-kafka:latest
    depends_on:
      - zookeeper
    ports:
      - 29092:29092
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      TOPIC_AUTO_CREATE: "true"
      TOPIC_CREATE_BACKOFF_MS: 120000

  web:
    image: oslcapi
    depends_on:
      - kafka
    build: .
    command: flask run -h 0.0.0.0 --cert=/code/certs/cert.pem --key=/code/certs/privkey.pem
    env_file:
      - ./.flaskenv
    environment:
      - DATABASE_URI=sqlite:////db/oslcapi.db
      - GOOGLE_APPLICATION_CREDENTIALS=/code/gcp/gcp_credentials.json
    volumes:
      - ./oslcapi:/code/oslcapi
      - ./db/:/db/
      - ./gcp_credentials.json:/code/gcp/gcp_credentials.json
      - ./cert.pem:/code/certs/cert.pem
      - ./privkey.pem:/code/certs/privkey.pem
    ports:
      - "5001:5000"