# WARNING: this file is not suitable for production, please use with caution
version: '3'

services:
  web:
    image: oslcapi
    build: .
    command: flask run -h 0.0.0.0 --cert=/home/oslc_tfm_gcp/dehydrated/certs/tfm-google.duckdns.org/cert.pem --key=/home/oslc_tfm_gcp/dehydrated/certs/tfm-google.duckdns.org/privkey.pem
    env_file:
      - ./.flaskenv
    environment:
      - DATABASE_URI=sqlite:////db/oslcapi.db
      - GOOGLE_APPLICATION_CREDENTIALS=/code/gcp/gcp_credentials.json
    volumes:
      - ./oslcapi:/code/oslcapi
      - ./db/:/db/
      - ./gcp_credentials.json:/code/gcp/gcp_credentials.json
    ports:
      - "5001:5000"