# WARNING: this file is not suitable for production, please use with caution
version: '3'

services:
  events:
    image: oslcapi-1
    build: .
    command: flask run -h 0.0.0.0 --port 5002
    env_file:
      - ./.flaskenv
    environment:
      - DATABASE_URI=sqlite:////db/oslcapi.db
      - GOOGLE_APPLICATION_CREDENTIALS=/code/gcp/gcp_credentials.json
    volumes:
      - ./oslcapi:/code/oslcapi
      - ./db/:/db/
      - ./gcp_credentials.json:/code/gcp/gcp_credentials.json
      - ./cert.pem:/code/certs/cert.pem
      - ./privkey.pem:/code/certs/privkey.pem
    ports:
      - "5002:5002"
